#!/usr/bin/env python
"""
Scrape an Instagram user's feed and store the files on S3

"""
import os

import requests

from instagram.client import InstagramAPI


INSTAGRAM_SECRET = os.getenv("INSTAGRAM_CLIENT_SECRET")
INSTAGRAM_TOKEN = os.getenv("INSTAGRAM_ACCESS_TOKEN")


def scrape_images():
    api = InstagramAPI(
        access_token=INSTAGRAM_TOKEN, client_secret=INSTAGRAM_SECRET)
    next_url = _get_images(api)
    while next_url:
        next_url = _get_images(api)


def _get_images(api):
    posts, next_url = api.user_recent_media()
    for post in posts:
        if _scrape_image_from_post(post):
            next_url = None
            break
    return next_url


def _scrape_image_from_post(post):
    img_data, hash = _download_image(post.get_standard_resolution_url())


def _download_image(url):
    img_data = requests.get(url).content
    return img_data

if __name__ == '__main__':
    scrape_images()
