/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Waypoint struct {
	// The location along the route that the waypoint is closest to
	Latlng *LatLng `json:"latlng,omitempty"`
	// A location off of the route that the waypoint is (optional)
	TargetLatlng *LatLng `json:"target_latlng,omitempty"`
	// Categories that the waypoint belongs to
	Categories []string `json:"categories,omitempty"`
	// A title for the waypoint
	Title string `json:"title,omitempty"`
	// A description of the waypoint (optional)
	Description string `json:"description,omitempty"`
	// The number meters along the route that the waypoint is located
	DistanceIntoRoute int32 `json:"distance_into_route,omitempty"`
}
