/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UpdatableActivity struct {
	// Whether this activity is a commute
	Commute bool `json:"commute,omitempty"`
	// Whether this activity was recorded on a training machine
	Trainer bool `json:"trainer,omitempty"`
	// Whether this activity is muted
	HideFromHome bool `json:"hide_from_home,omitempty"`
	// The description of the activity
	Description string `json:"description,omitempty"`
	// The name of the activity
	Name string `json:"name,omitempty"`
	// Deprecated. Prefer to use sport_type. In a request where both type and sport_type are present, this field will be ignored
	Type_     *ActivityType `json:"type,omitempty"`
	SportType *SportType    `json:"sport_type,omitempty"`
	// Identifier for the gear associated with the activity. ‘none’ clears gear from activity
	GearId string `json:"gear_id,omitempty"`
}
